apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-redis",
            "image": "library/redis:3.2",
            "command": ["bash", "-c", "
              set -ex\n
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1\n
              [[ -f /mnt/conf/redis.conf ]] && exit 0\n
              ordinal=${BASH_REMATCH[1]}\n
              # Copy appropriate conf.d files from config-map to emptyDir.\n
              cp /mnt/config-map/shared.conf /mnt/conf/redis.conf\n
              # ordinal 0 is the first host\n
              if [[ $ordinal -eq 0 ]]; then\n
                cat /mnt/config-map/master.conf >> /mnt/conf/redis.conf\n
              else\n
                cat /mnt/config-map/slave.conf >> /mnt/conf/redis.conf\n
              fi\n
            "],
            "volumeMounts": [
              {"name": "data", "mountPath": "/data"},
              {"name": "conf", "mountPath": "/mnt/conf"},
              {"name": "config-map", "mountPath": "/mnt/config-map"}
            ]
          }
        ]'
    spec:
      containers:
      - name: redis
        command: ["redis-server", "/etc/redis/redis.conf"]
        image: library/redis:3.2
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /etc/redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/usr/local/bin/redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: config-map
        configMap:
          name: redis
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: conf
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
