apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
data:
  sentinel.conf: |
    # sentinel config
    port 26379
    sentinel monitor redis redis-0.redis 6379 2
    sentinel down-after-milliseconds redis 5000
